name: Security Vulnerability Report
description: Report a security vulnerability in the Agent Mesh Protocol (Private)
title: "[SECURITY] "
labels: ["security", "vulnerability", "needs-immediate-attention"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: Security Vulnerability Reporting** ⚠️
        
        Thank you for helping keep AMP secure! Please follow our responsible disclosure process:
        
        🔒 **For Private Reporting (Recommended):**
        - Use GitHub's [Private Vulnerability Reporting](https://github.com/agentmeshprotocol/agentmeshprotocol/security/advisories/new)
        - Email security@agentmeshprotocol.io
        - Contact maintainers directly for critical issues
        
        ⚠️ **Only use this public template for:**
        - General security improvement suggestions
        - Non-sensitive security questions
        - Security feature requests
        
        **DO NOT** include sensitive details in this public issue that could help attackers.

  - type: dropdown
    id: report-type
    attributes:
      label: Report Type
      description: What type of security issue is this?
      options:
        - Security improvement suggestion
        - Security feature request
        - Security documentation issue
        - General security question
        - Potential vulnerability (use private reporting!)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security concern?
      options:
        - Low (security enhancement)
        - Medium (potential risk)
        - High (significant risk - use private reporting!)
        - Critical (immediate risk - use private reporting!)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: Which area of security does this relate to?
      options:
        - Authentication
        - Authorization
        - Message Security
        - Transport Security
        - Data Protection
        - Input Validation
        - Cryptography
        - Access Control
        - Audit/Logging
        - Configuration Security
        - Dependency Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security concern or improvement (avoid sensitive details)
      placeholder: |
        General description of the security issue or improvement.
        Focus on the concept rather than specific exploitation details.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could be the impact if this isn't addressed?
      placeholder: |
        - What systems or data could be affected?
        - What are the potential consequences?
        - Who would be impacted?

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of AMP are affected?
      placeholder: |
        - Protocol specification
        - Reference implementations
        - SDK components
        - Documentation
        - Examples
      value: |
        - [ ] Protocol specification
        - [ ] Reference implementations  
        - [ ] SDK components
        - [ ] Documentation
        - [ ] Examples

  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: "e.g., 1.0.0-1.2.0, all versions, latest"

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Relevant environment details (if applicable)
      placeholder: |
        - Deployment environment
        - Network configuration
        - Security controls in place
        - Framework versions

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Any suggestions for addressing this issue?
      placeholder: |
        - Immediate workarounds
        - Long-term solutions
        - Best practices to implement
        - Configuration changes

  - type: textarea
    id: references
    attributes:
      label: References
      description: Relevant security resources or standards
      placeholder: |
        - OWASP guidelines
        - Security best practices
        - Relevant CVEs
        - Security research papers

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure Agreement
      options:
        - label: I understand the importance of responsible disclosure
          required: true
        - label: I will not publicly disclose sensitive details until resolved
          required: true
        - label: I will use private channels for actual vulnerabilities
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🛡️ Security Contact Information
        
        - **Private Vulnerability Reports**: [GitHub Security Advisories](https://github.com/agentmeshprotocol/agentmeshprotocol/security/advisories/new)
        - **Email**: security@agentmeshprotocol.io
        - **PGP Key**: [Available on our website](https://agentmeshprotocol.io/security)
        
        ### ⏰ Response Timeline
        - **Acknowledgment**: Within 48 hours
        - **Initial Assessment**: Within 1 week
        - **Resolution**: Varies by severity
        
        Thank you for helping keep AMP secure! 🔒